apiVersion: v1
kind: Service
metadata:
  name: tusharmoviesdb-service  # Updated service name
  namespace: default
  labels:
    app: tusharmoviesdb  # Updated app name
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 80           # Port to access the app
      targetPort: 80      # Target port for Angular app
  selector:
    app: tusharmoviesdb  # Updated app name
